name: teamup
description: "Une application d'amusement pour les amateurs de football"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  motion_tab_bar_v2: ^0.3.0
  cupertino_icons: ^1.0.8
  rive: ^0.13.13
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  rive_animated_icon: ^2.0.3
  device_preview: ^1.2.0
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.3
  google_fonts: ^6.2.1
  toastification: ^2.3.0
  fluttertoast: ^8.2.10
  flutter_google_maps_webservices: ^1.1.1
  google_places_flutter: ^2.0.9
  intl: ^0.19.0
  icons_plus: ^5.0.0
  shared_preferences: ^2.3.5
  uni_links: ^0.5.1
  app_links: ^6.3.3
  settings_ui: ^2.0.2
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.10.0
  web_socket_channel: ^3.0.1
  flutter_localization: ^0.3.0
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.2
  flutter_local_notifications: ^18.0.1
  onesignal_flutter: ^5.2.9
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  googleapis_auth: ^1.6.0
  go_router: ^6.0.0
  easy_localization: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/football.jpg
    - assets/images/terrain.png
    - assets/logos/google_light.png
    - assets/logos/logo_green.png
    - assets/logos/grey_logo.png
    - assets/images/ia.png
    - assets/images/image_empty.png
    - assets/images/marker.png
    - assets/map_style_dark.json
    - assets/translations/

  uses-material-design: true