// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOaKxBOMivKnWYai5cCtfVbOWXE31Ccxk',
    appId: '1:812994509921:web:01d3dd855c5b66ed1b7e20',
    messagingSenderId: '812994509921',
    projectId: 'notification-push-40d24',
    authDomain: 'notification-push-40d24.firebaseapp.com',
    storageBucket: 'notification-push-40d24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7DDmuslgRHNQJDKz8qgiA5WX2dwpU30o',
    appId: '1:812994509921:android:7ca93e219e7a4d291b7e20',
    messagingSenderId: '812994509921',
    projectId: 'notification-push-40d24',
    storageBucket: 'notification-push-40d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf2lXwk_IsoSWiuRRb0hFD9cDJJ5IkZNI',
    appId: '1:812994509921:ios:13bc03a85d365fe51b7e20',
    messagingSenderId: '812994509921',
    projectId: 'notification-push-40d24',
    storageBucket: 'notification-push-40d24.firebasestorage.app',
    iosBundleId: 'com.teamup.app',
  );

}